from __future__ import annotations

import argparse
import math
import os
from datetime import UTC, datetime, timedelta
from urllib.parse import urlparse

import psycopg
from dotenv import load_dotenv

TAGS = (
    ("e2e-depth", "Глубина E2E", "м", "Бурение"),
    ("e2e-pressure", "Давление E2E", "бар", "Гидравлика"),
    ("e2e-live", "Изменяемый E2E", "об/мин", "Live"),
)


def _edge_ids() -> tuple[str, str, str]:
    return (
        os.getenv("E2E_EDGE_ID", "").strip() or "e2e-main",
        os.getenv("E2E_NO_VIDEO_EDGE_ID", "").strip() or "e2e-no-video",
        os.getenv("E2E_VIDEO_EDGE_ID", "").strip() or "e2e-video",
    )


def _require_safe_ids(edge_ids: tuple[str, str, str]) -> None:
    unsafe = [edge_id for edge_id in edge_ids if not edge_id.startswith("e2e-")]
    if unsafe:
        raise SystemExit(f"Seed разрешён только для edge ID с префиксом 'e2e-': {unsafe}")


def _values_for_timestamp(edge_id: str, timestamp: datetime, index: int) -> list[tuple[str, datetime, str, float]]:
    timestamp_without_tz = timestamp.replace(tzinfo=None)
    return [
        (edge_id, timestamp_without_tz, "e2e-depth", 1_500 + index * 0.15),
        (edge_id, timestamp_without_tz, "e2e-pressure", 125 + math.sin(index / 8) * 12),
        (edge_id, timestamp_without_tz, "e2e-live", 80 + math.sin(index / 3) * 8),
    ]


def _history_rows(edge_id: str, now: datetime) -> list[tuple[str, datetime, str, float]]:
    rows: list[tuple[str, datetime, str, float]] = []
    start = now - timedelta(days=31)
    for hour in range(31 * 24 + 1):
        rows.extend(_values_for_timestamp(edge_id, start + timedelta(hours=hour), hour))

    recent_start = now - timedelta(hours=24)
    for step in range(24 * 12 + 1):
        rows.extend(_values_for_timestamp(edge_id, recent_start + timedelta(minutes=step * 5), step))
    return rows


def seed(database_url: str, edge_ids: tuple[str, str, str]) -> None:
    edge_id, no_video_edge_id, video_edge_id = edge_ids
    now = datetime.now(UTC).replace(microsecond=0)
    history_rows = _history_rows(edge_id, now)

    with psycopg.connect(database_url) as connection, connection.cursor() as cursor:
        cursor.executemany(
            """
            INSERT INTO edge (id, name, parent_id)
            VALUES (%s, %s, NULL)
            ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
            """,
            [
                (edge_id, "E2E — основная буровая"),
                (no_video_edge_id, "E2E — без камер"),
                (video_edge_id, "E2E — видео"),
            ],
        )
        cursor.executemany(
            """
            INSERT INTO tag (id, name, min, max, comment, unit_of_measurement, precision, tag_group)
            VALUES (%s, %s, 0, 10000, 'Generated by drill-cloud-test', %s, 2, %s)
            ON CONFLICT (id) DO UPDATE SET
              name = EXCLUDED.name,
              unit_of_measurement = EXCLUDED.unit_of_measurement,
              tag_group = EXCLUDED.tag_group
            """,
            TAGS,
        )
        cursor.executemany(
            """
            INSERT INTO current (edge, tag, value, "updatedAt")
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (edge, tag) DO UPDATE SET value = EXCLUDED.value, "updatedAt" = EXCLUDED."updatedAt"
            """,
            [
                (edge_id, "e2e-depth", 1_612.5, now.replace(tzinfo=None)),
                (edge_id, "e2e-pressure", 128.4, now.replace(tzinfo=None)),
                (edge_id, "e2e-live", 82.0, now.replace(tzinfo=None)),
            ],
        )
        cursor.execute("DELETE FROM history WHERE edge = %s AND tag = ANY(%s)", (edge_id, [tag[0] for tag in TAGS]))
        cursor.executemany(
            'INSERT INTO history (edge, "timestamp", tag, value) VALUES (%s, %s, %s, %s)',
            history_rows,
        )

        cursor.execute("DELETE FROM camera WHERE edge = ANY(%s)", ([video_edge_id, no_video_edge_id],))
        video_url = os.getenv("E2E_VIDEO_WS_URL", "").strip()
        if video_url:
            parsed = urlparse(video_url)
            if parsed.scheme not in {"ws", "wss"} or not parsed.netloc:
                raise SystemExit("E2E_VIDEO_WS_URL должен иметь вид ws://host/path или wss://host/path")
            source = f"{parsed.netloc}{parsed.path}"
            if parsed.query:
                source = f"{source}?{parsed.query}"
            cursor.execute(
                "INSERT INTO camera (edge, name, protocol, source) VALUES (%s, %s, %s, %s)",
                (video_edge_id, "E2E камера", parsed.scheme, source),
            )

    print(f"Seed completed: edge={edge_id}, history_rows={len(history_rows)}")


def cleanup(database_url: str, edge_ids: tuple[str, str, str]) -> None:
    with psycopg.connect(database_url) as connection, connection.cursor() as cursor:
        tag_ids = [tag[0] for tag in TAGS]
        cursor.execute("DELETE FROM camera WHERE edge = ANY(%s)", (list(edge_ids),))
        cursor.execute("DELETE FROM history WHERE edge = ANY(%s) AND tag = ANY(%s)", (list(edge_ids), tag_ids))
        cursor.execute("DELETE FROM current WHERE edge = ANY(%s) AND tag = ANY(%s)", (list(edge_ids), tag_ids))
        cursor.execute("DELETE FROM edge WHERE id = ANY(%s)", (list(edge_ids),))
        cursor.execute("DELETE FROM tag WHERE id = ANY(%s)", (tag_ids,))
    print(f"Cleanup completed: {', '.join(edge_ids)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare deterministic Drill Cloud E2E data")
    parser.add_argument("command", choices=("seed", "cleanup"), nargs="?", default="seed")
    args = parser.parse_args()

    load_dotenv()
    edge_ids = _edge_ids()
    _require_safe_ids(edge_ids)
    database_url = os.getenv("E2E_DATABASE_URL", "").strip()
    if not database_url:
        raise SystemExit("Задайте E2E_DATABASE_URL в .env")

    seed(database_url, edge_ids) if args.command == "seed" else cleanup(database_url, edge_ids)


if __name__ == "__main__":
    main()
